emit: [
  "@azure-tools/typespec-autorest",
  "@azure-tools/typespec-csharp",
  "@azure-tools/typespec-python"
]
options:
  "@azure-tools/typespec-autorest":
    "output-file": "BatchService.json"
  "@azure-tools/typespec-csharp":
    clear-output-folder: true
    model-namespace: false
    namespace: Azure.Compute.Batch
  "@azure-tools/typespec-java":
    namespace: "com.azure.compute.batch"
    service-name: "Batch"
    partial-update: true  
